server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/inventory_auth_db?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:himanshu@123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000
