server:
  port: 9090

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  application:
    name: website-controller
  
logging:
  level:
    org.springframework.web: INFO
    com.bridgelabz.website: DEBUG

# Microservices URLs (To be used by Feign Clients)
services:
  auth: ${AUTH_SERVICE_URL:http://localhost:8081}
  product: ${PRODUCT_SERVICE_URL:http://localhost:8082}
  warehouse: ${WAREHOUSE_SERVICE_URL:http://localhost:8083}
  supplier: ${SUPPLIER_SERVICE_URL:http://localhost:8084}
  purchase: ${PURCHASE_SERVICE_URL:http://localhost:8085}
  movement: ${MOVEMENT_SERVICE_URL:http://localhost:8086}
  alert: ${ALERT_SERVICE_URL:http://localhost:8087}
  sales: ${SALES_SERVICE_URL:http://localhost:8088}
  report: ${REPORT_SERVICE_URL:http://localhost:8089}

